### ISSUE TITLE
thoth-messaging==0.3.3 cannot be installed

### ISSUE THREAD

**Issue by pacospace** [thoth-station/messaging#113]
Using `pipenv, version 2020.1.29`

Pipfile:
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
thoth-lab = ">=0.1.8"
thoth-common= "*"
thoth-messaging= "*"

[requires]
python_version = "3.6"

```

Running pipenv

```
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Building requirements...
Resolving dependencies...
⠦ Locking...
                          ROUND 1                           
✘ Locking Failed! 
Current constraints:
  thoth-common
  thoth-lab>=0.1.8
  thoth-messaging

Finding the best candidates:
  found candidate thoth-common==0.12.4 (constraint was <any>)
  found candidate thoth-lab==0.1.8 (constraint was >=0.1.8)
  found candidate thoth-messaging==0.3.3 (constraint was <any>)

Finding secondary dependencies:
  thoth-common==0.12.4 not in cache, need to check index
  thoth-common==0.12.4      requires argo-workflows<3.0,>=2.0, attrdict, attrs, daiquiri, jsonformatter, openshift~=0.10.0, pyyaml, requests, rfc5424-logging-handler, sentry-sdk
  thoth-lab==0.1.8 not in cache, need to check index
  thoth-lab==0.1.8          requires autopep8, cufflinks, ipykernel, ipython, jupyter-contrib-nbextensions, jupyter-require, matplotlib, networkx, pandas, pandas-profiling, plotly, prettyprinter, requests, thoth-storages
  thoth-messaging==0.3.3 not in cache, need to check index
Traceback (most recent call last):
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 807, in <module>
    main()
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 803, in main
    parsed.requirements_dir, parsed.packages, parse_only=parsed.parse_only)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 785, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 753, in resolve_packages
    requirements_dir=requirements_dir,
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 736, in resolve
    req_dir=requirements_dir
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/utils.py", line 1371, in resolve_deps
    req_dir=req_dir,
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/utils.py", line 1078, in actually_resolve_deps
    resolver.resolve()
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/utils.py", line 799, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 205, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 300, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 202, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 350, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 309, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 301, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 248, in _get_abstract_dist_for
    self.require_hashes
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 342, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 158, in prep_for_dist
    self.req.prepare_metadata()
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 530, in prepare_metadata
    self.run_egg_info()
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 610, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmph_ztoe11source/thoth-messaging/
ROUND 1                           
Current constraints:
  thoth-common
  thoth-lab>=0.1.8
  thoth-messaging

Finding the best candidates:
  found candidate thoth-common==0.12.4 (constraint was <any>)
  found candidate thoth-lab==0.1.8 (constraint was >=0.1.8)
  found candidate thoth-messaging==0.3.3 (constraint was <any>)

Finding secondary dependencies:
  thoth-common==0.12.4 not in cache, need to check index
  thoth-common==0.12.4      requires argo-workflows<3.0,>=2.0, attrdict, attrs, daiquiri, jsonformatter, openshift~=0.10.0, pyyaml, requests, rfc5424-logging-handler, sentry-sdk
  thoth-lab==0.1.8 not in cache, need to check index
  thoth-lab==0.1.8          requires autopep8, cufflinks, ipykernel, ipython, jupyter-contrib-nbextensions, jupyter-require, matplotlib, networkx, pandas, pandas-profiling, plotly, prettyprinter, requests, thoth-storages
  thoth-messaging==0.3.3 not in cache, need to check index
Traceback (most recent call last):
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 807, in <module>
    main()
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 803, in main
    parsed.requirements_dir, parsed.packages, parse_only=parsed.parse_only)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 785, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 753, in resolve_packages
    requirements_dir=requirements_dir,
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 736, in resolve
    req_dir=requirements_dir
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/utils.py", line 1371, in resolve_deps
    req_dir=req_dir,
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/utils.py", line 1078, in actually_resolve_deps
    resolver.resolve()
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/utils.py", line 799, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 205, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 300, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 202, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 350, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 309, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 301, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 248, in _get_abstract_dist_for
    self.require_hashes
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 342, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 158, in prep_for_dist
    self.req.prepare_metadata()
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 530, in prepare_metadata
    self.run_egg_info()
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 610, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/fmurdaca/.local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmph_ztoe11source/thoth-messaging/
```

**Comment by pacospace** [comment]
Solved with new release `thoth-messaging==0.3.4`. Thanks @fridex
